export const columns = [
  { accessorKey: "id", header: "S No." },
  { accessorKey: "form_no", header: "Form No." },
  { accessorKey: "name", header: "Name" },
  { accessorKey: "father_name", header: "Father Name" },
  { accessorKey: "dob", header: "Date of Birth" },
  { accessorKey: "domicile", header: "Domicile" },
  { accessorKey: "cnic", header: "CNIC" },
  { accessorKey: "email", header: "Email" },
  { accessorKey: "mobile_no", header: "Mobile No" },
  { accessorKey: "landline_no", header: "Landline Number" },
  { accessorKey: "postal_address", header: "Postal Address" },
  { accessorKey: "permanent_address", header: "Permanent Address" },
  { accessorKey: "current_student", header: "Current Student" },
  { accessorKey: "hifz_e_quran", header: "Hifz-e-Quran" },
  { accessorKey: "hifz_marks", header: "Hifz Marks" },
  { accessorKey: "emp_quota", header: "Emp Quota" },
  { accessorKey: "fata", header: "FATA" },
  { accessorKey: "overseas", header: "Overseas" },
  { accessorKey: "ssc_obtain", header: "SSC Obtain" },
  { accessorKey: "ssc_total", header: "SSC Total" },
  { accessorKey: "intermediate_type", header: "Intermediate Type" },
  { accessorKey: "intermediate_group", header: "Intermediate Group" },
  { accessorKey: "intermediate_obtain", header: "Intermediate Obtain" },
  { accessorKey: "intermediate_total", header: "Intermediate Total" },
  { accessorKey: "etea_rollno", header: "ETEA RollNo" },
  { accessorKey: "etea_obtain", header: "ETEA Obtain" },
  { accessorKey: "etea_total", header: "ETEA Total" },
  { accessorKey: "aggregate", header: "Aggregate" },
  { accessorKey: "matched_preference", header: "Matched Preference" }, // New column
];